// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNsDYDw56cKNPymyLSQd737RVjR2HxVyM',
    appId: '1:432059990875:web:5fb4e7c054806b2be6d07e',
    messagingSenderId: '432059990875',
    projectId: 'voluntarius-h4h',
    authDomain: 'voluntarius-h4h.firebaseapp.com',
    storageBucket: 'voluntarius-h4h.appspot.com',
    measurementId: 'G-MWNQ1WHR0H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8KmYAvpHAZKEkNXFK2WbLzm_DlGqe_O4',
    appId: '1:432059990875:android:04f57b610bbffa2ae6d07e',
    messagingSenderId: '432059990875',
    projectId: 'voluntarius-h4h',
    storageBucket: 'voluntarius-h4h.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3lsRXpi-vgeUjgfLHQ2S0rtls52fqKYY',
    appId: '1:432059990875:ios:0f1f63800a077330e6d07e',
    messagingSenderId: '432059990875',
    projectId: 'voluntarius-h4h',
    storageBucket: 'voluntarius-h4h.appspot.com',
    iosClientId: '432059990875-8vlpq05dm23cji95aokdpevkn26f0a8f.apps.googleusercontent.com',
    iosBundleId: 'app.web.voluntarius',
  );
}
